"""Regression contracts for the PR review/fix automation.

These checks are intentionally structural. The workflow runs on GitHub, but
the failure modes they guard are local policy regressions: self-triggering
routine comments, stale post-merge fires, unbound bot authorization, and
merges with unresolved current review threads.
"""

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
WORKFLOW = ROOT / ".github/workflows/pr-agent.yml"
TEST_WORKFLOW = ROOT / ".github/workflows/test.yml"
FULL_TEST_WORKFLOW = ROOT / ".github/workflows/test-main.yml"
FIRE_ACTION = ROOT / ".github/actions/fire-routine/action.yml"
MERGE_ACTION = ROOT / ".github/actions/pr-merge-ready/action.yml"
ROUTINE_PROMPT = ROOT / "docs/pr-agent-routine-prompt.md"


def _read(path):
    return path.read_text(encoding="utf-8")


def test_automation_contract_inputs_run_the_python_suite():
    test_workflow = _read(TEST_WORKFLOW)

    assert 'path.startsWith(".github/actions/")' in test_workflow
    assert 'path === ".github/workflows/pr-agent.yml"' in test_workflow
    assert 'path === "docs/pr-agent-routine-prompt.md"' in test_workflow


def test_full_suite_label_overrides_path_classification():
    workflow = _read(TEST_WORKFLOW)

    assert workflow.index("const full =") < workflow.index("const python =")
    assert "const python = full || touchesTestWorkflow ||" in workflow


def test_impact_map_requires_success_and_uploads_from_hidden_directory():
    workflow = _read(FULL_TEST_WORKFLOW)

    assert "&& steps.tests.outputs.exit-code == '0'" in workflow
    assert "steps.tests.outputs.exit-code == '1'" not in workflow
    condition = "if: ${{ !cancelled() && steps.build-map.outcome == 'success' }}"
    assert workflow.count(condition) == 2
    assert "include-hidden-files: true" in workflow


def test_review_events_are_collapsed_and_generated_feedback_is_ignored():
    workflow = _read(WORKFLOW)

    assert "cancel-in-progress: true" in workflow
    assert "<!-- pr-agent-generated -->" in workflow
    assert "Generated by [Claude Code]" in workflow
    assert "!contains(github.event.comment.body, '<!-- pr-agent-generated -->')" not in workflow
    assert "!contains(github.event.review.body || '', '<!-- pr-agent-generated -->')" not in workflow
    assert "!endsWith(github.event.comment.body, '<!-- pr-agent-generated -->')" in workflow
    assert "!endsWith(github.event.review.body || '', '<!-- pr-agent-generated -->')" in workflow
    assert "--remove-label pr-agent-needs-human" in workflow
    assert workflow.count("uses: actions/checkout@v5") == workflow.count(
        "ref: ${{ github.event.repository.default_branch }}"
    )
    assert "issue_comment:\n    types: [created, edited]" in workflow
    assert "pull_request_review:\n    types: [submitted, edited, dismissed]" in workflow
    assert "pull_request_review_comment:\n    types: [edited]" in workflow
    assert "(github.event.review.state != 'approved' || github.event.action == 'edited')" in workflow


def test_concurrency_is_scoped_per_task_and_never_workflow_wide():
    workflow = _read(WORKFLOW)

    # A workflow-wide `pr-agent-<PR>` group with cancel-in-progress: true
    # would let an ignored generated comment cancel an in-flight `/merge`
    # or approval-driven merge run for the same PR. Keep the
    # concurrency block per-job instead.
    stripped = "\n".join(line for line in workflow.splitlines() if not line.lstrip().startswith("#"))
    assert "\nconcurrency:\n" not in stripped

    # Review-fix firers share a per-PR group so newer reviews collapse
    # earlier ones without touching merge or CI-fix work.
    review_group_issue = "group: pr-agent-review-fix-${{ github.event.issue.number }}"
    review_group_pr = "group: pr-agent-review-fix-${{ github.event.pull_request.number }}"
    assert workflow.count(review_group_issue) == 1  # fix-comment-feedback only
    assert workflow.count(review_group_pr) == 3  # reviews + Codex + inline comments
    human_reconcile_group = "group: pr-agent-human-reconcile-${{ github.event.issue.number }}"
    assert human_reconcile_group in workflow
    human_group_idx = workflow.index(human_reconcile_group)
    human_group_end = workflow.index("\n", human_group_idx)
    human_group_next = workflow.index("\n", human_group_end + 1)
    assert "cancel-in-progress: false" in workflow[human_group_end:human_group_next]

    # Each merge authorization gets a distinct non-cancellable group, so one
    # valid pending authorization cannot evict another.
    assert (
        "group: pr-agent-merge-approval-${{ github.event.pull_request.number }}-${{ github.event.review.id }}"
    ) in workflow
    assert ("group: pr-agent-merge-command-${{ github.event.issue.number }}-${{ github.event.comment.id }}") in workflow
    assert "group: pr-agent-merge-tests-${{ github.event.workflow_run.id }}" in workflow
    assert (
        "group: pr-agent-merge-codex-${{ matrix.target.pr }}-${{ matrix.target.reaction_id }}"
    ) in workflow
    assert "needs: authorize_approval" in workflow
    assert "if: needs.authorize_approval.outputs.authorized == 'true'" in workflow
    assert "needs: authorize_merge_command" in workflow
    assert "if: needs.authorize_merge_command.outputs.authorized == 'true'" in workflow

    # fix-ci derives the PR number from `workflow_run.pull_requests[0]`
    # so unrelated PRs sharing a default-branch SHA don't cancel each
    # other's CI-repair runs.
    assert (
        "group: pr-agent-ci-fix-${{ github.event.workflow_run.pull_requests[0].number "
        "|| github.event.workflow_run.head_sha }}"
    ) in workflow

    # Conflict discovery is one global scan, while each repair joins the same
    # per-PR lane as review reconciliation.
    discover_group = "group: pr-agent-discover-conflicts-${{ github.event.pull_request.number || 'main' }}"
    assert discover_group in workflow
    assert "group: pr-agent-review-fix-${{ matrix.target.pr }}" in workflow

    # Guard against a review-fix job regressing to `cancel-in-progress: false`,
    # which would preserve a queue of stale reviews. Every review-fix,
    # CI-fix, and conflict-scan group must collapse; only merge groups
    # keep `false` so an in-flight authorization is not cancelled by a
    # newer approval event that also passes the gate.
    collapse_groups = (
        review_group_issue,
        review_group_pr,
        "group: pr-agent-ci-fix-",
        discover_group,
        "group: pr-agent-review-fix-${{ matrix.target.pr }}",
    )
    for group_prefix in collapse_groups:
        idx = workflow.find(group_prefix)
        while idx != -1:
            end_of_line = workflow.find("\n", idx)
            next_line_start = end_of_line + 1
            next_line_end = workflow.find("\n", next_line_start)
            next_line = workflow[next_line_start:next_line_end]
            assert "cancel-in-progress: true" in next_line, (
                f"{group_prefix!r} must set cancel-in-progress: true, got {next_line!r}"
            )
            idx = workflow.find(group_prefix, next_line_end)


def test_merge_command_does_not_double_fire_the_review_fix_routine():
    workflow = _read(WORKFLOW)

    # `/merge <sha>` on a claude-agent PR is a merge command handled by
    # `merge-on-command`. If `fix-comment-feedback` also fired on it, the
    # routine could push a new head and invalidate the human's SHA-bound
    # merge authorization before the synchronous merge check.
    assert "!startsWith(github.event.comment.body, '/merge ')" not in workflow
    assert 'elif [[ "$COMMENT_BODY" =~ ^/merge[[:space:]]+' in workflow
    assert "Exact /merge command is handled by the merge-authorization lane." in workflow


def test_ci_fix_binds_to_failing_run_head_not_live_pr_head():
    workflow = _read(WORKFLOW)

    # When Tests for commit A completes after the PR has advanced to
    # commit B, passing the live PR head B as expected-head would let the
    # routine edit B while diagnosing A's failure logs. The stale-head
    # skip and the expected-head passthrough must both key on
    # `github.event.workflow_run.head_sha`, not the current PR head.
    assert "WORKFLOW_RUN_HEAD_SHA: ${{ github.event.workflow_run.head_sha }}" in workflow
    assert 'if [[ "$live_head" != "$WORKFLOW_RUN_HEAD_SHA" ]]' in workflow
    assert 'echo "head_sha=$WORKFLOW_RUN_HEAD_SHA"' in workflow


def test_routine_fire_rechecks_live_pr_state_and_expected_head():
    action = _read(FIRE_ACTION)

    assert "--json state,headRefOid,headRepositoryOwner,headRepository" in action
    assert 'if [[ "${state}" != "OPEN" ]]' in action
    assert 'if [[ "${head_repo}" != "${REPO}" ]]' in action
    assert '"${current_head}" != "${EXPECTED_HEAD}"*' in action
    assert "Expected head: ${current_head}" in action
    assert "max-review-fix-rounds" not in action
    assert "MAX_REVIEW_FIX_ROUNDS" not in action
    assert "prior_rounds" not in action
    assert 'echo "fired=false" >> "$GITHUB_OUTPUT"' in action
    assert 'echo "fired=true" >> "$GITHUB_OUTPUT"' in action

    # Review objects stay attached to their original commit even after edits.
    # Review routes therefore let the forwarder bind its verified live head;
    # event-bound heads remain only on sources whose subject is a specific run.
    assert "expected-head: ${{ github.event.review.commit_id }}" not in _read(WORKFLOW)


def test_human_and_codex_merge_authorizations_are_head_bound():
    workflow = _read(WORKFLOW)

    human_actor_line = next(line for line in workflow.splitlines() if "HUMAN_MERGE_ACTORS:" in line)
    assert "jss367" in human_actor_line
    assert "bot" not in human_actor_line
    assert 'CODEX_MERGE_ACTOR: "chatgpt-codex-connector[bot]"' in workflow
    assert "merge-on-thumbsup:" not in workflow
    assert "startsWith(github.event.comment.body, '/merge ')" in workflow
    assert "approved-head: ${{ github.event.review.commit_id }}" in workflow
    assert "approved-head: ${{ needs.authorize_merge_command.outputs.approved_head }}" in workflow
    assert 'live_head" != "$REVIEW_HEAD' in workflow
    assert 'live_head" != "$approved_head"*' in workflow

    # Reactions have no webhook, so discovery runs on an optional Codex comment,
    # successful Tests, and a polling fallback. A generic +1 comment is never
    # considered authorization. Codex reactions carry no reviewed SHA, so the
    # trusted connector is treated as approving the live PR state; requiring
    # the reaction to postdate an exact-head Tests run invalidates reactions
    # that were already present before a later push.
    assert 'cron: "*/15 * * * *"' in workflow
    assert "workflow_dispatch:" in workflow
    assert "discover-codex-merge-authorizations:" in workflow
    assert "github.actor == 'chatgpt-codex-connector[bot]'" in workflow
    assert "github.event.workflow_run.conclusion == 'success'" in workflow
    assert 'select(.content == "+1")' in workflow
    assert 'select(.created_at > $tests_started_at)' in workflow
    assert '--json databaseId,headSha,createdAt' in workflow
    assert 'select((.headSha | ascii_downcase) == $head)' in workflow
    assert 'tests_run_id: $authorization' not in workflow
    assert 'tests_run_id: $tests_run_id' in workflow
    assert "codex-reaction-id: ${{ matrix.target.reaction_id }}" in workflow
    assert "codex-tests-run-id: ${{ matrix.target.tests_run_id }}" in workflow


def test_merge_gate_requires_live_head_and_resolved_current_threads():
    action = _read(MERGE_ACTION)

    assert 'if [[ "$state" != "OPEN" ]]' in action
    assert 'if [[ "$head_sha" != "$APPROVED_HEAD"* ]]' in action
    assert 'approval_state" != "APPROVED"' in action
    assert 'approval_head" != "$head_sha"' in action
    assert 'approval_time" != "$AUTHORIZED_AT"' in action
    assert "repos/${REPO}/issues/comments/${MERGE_COMMENT_ID}" in action
    assert 'merge_time" != "$AUTHORIZED_AT"' in action
    assert "has no live approval, merge-command, or Codex-review authorization" in action
    assert '"$authorization_count" -gt 1' in action
    assert '"$authorization_count" -eq 0' in action
    assert "repos/${REPO}/issues/${PR}/reactions" in action
    assert 'reaction_actor" != "chatgpt-codex-connector[bot]"' in action
    assert 'reaction_content" != "+1"' in action
    assert 'reaction_time" != "$AUTHORIZED_AT"' in action
    assert 'gh run view "$CODEX_TESTS_RUN_ID"' in action
    assert 'codex_tests_head" != "$head_sha"' in action
    assert 'codex_tests_event" != "pull_request"' in action
    assert 'codex_tests_workflow" != "Tests"' in action
    assert 'reaction_time" < "$codex_tests_started_at"' in action
    assert 'reaction_time" == "$codex_tests_started_at"' in action
    assert 'and .created_at == .updated_at' in action
    assert 'startswith("Codex Review: Didn\\u0027t find any major issues.")' in action
    assert '$head | startswith($reviewed_head)' in action
    assert "reviewThreads(first:100" in action
    assert ".isResolved == false and .isOutdated == false" in action
    assert 'if [[ "$unresolved" -gt 0 ]]' in action
    assert "reviewDecision" in action
    assert '"$review_decision" == "CHANGES_REQUESTED"' in action
    assert 'gh run list --repo "$REPO" --workflow Tests' in action
    assert ".headSha == $head" in action
    assert '"$test_status" != "completed"' in action
    assert '"$test_conclusion" != "success"' in action
    assert "select(.updated_at >= $authorized_at)" in action
    assert "select(.updated_at > $authorized_at)" in action
    assert "repos/${REPO}/pulls/${PR}/comments" in action
    assert ".updatedAt >= $authorized_at" in action
    assert "reviews(first:100" in action
    assert "nodes { submittedAt updatedAt state body authorAssociation author { login } }" in action
    assert '.state == "APPROVED"' in action
    assert ".updatedAt > .submittedAt" in action
    assert '.author.login == "chatgpt-codex-connector"' not in action
    assert '.state == "COMMENTED" or .state == "CHANGES_REQUESTED"' in action
    assert 'select((.body // "") | test("[^[:space:]]"))' in action
    assert 'endswith("<!-- pr-agent-generated -->")' in action
    assert 'endswith("Generated by [Claude Code](https://claude.ai/code)_")' in action
    assert 'contains("<!-- pr-agent-generated -->")' not in action
    assert 'test("^/merge[[:space:]]+[0-9a-fA-F]{7,40}[[:space:]]*$")' in action
    assert 'if [[ "$newer_feedback" -gt 0 ]]' in action
    assert "PR_AGENT_TITLE_$(openssl rand -hex 16)" in action
    assert 'while grep -Fqx "$title_delimiter"' in action
    assert "printf '%s\\n' \"${title}\"" in action
    assert 'echo "${title}"' not in action
    assert "title<<PR_AGENT_TITLE" not in action


def test_inline_comment_edits_wake_reconciliation_on_the_live_head():
    workflow = _read(WORKFLOW)

    start = workflow.index("  fix-inline-comment:")
    end = workflow.index("\n  # Auto-fix when the Tests workflow fails", start)
    block = workflow[start:end]
    assert "github.event_name == 'pull_request_review_comment'" in block
    assert "pull_request_review_comment:\n    types: [created, edited]" not in workflow
    assert "github.event.pull_request.state == 'open'" in block
    assert "Task: address-review" in block
    assert "Review body:" in block
    assert "github.event.comment.body" in block
    assert "expected-head:" not in block


def test_routine_contract_is_state_based_quiet_and_resolves_addressed_threads():
    prompt = _read(ROUTINE_PROMPT)

    assert "silent no-op: do not push and do not post a comment" in prompt
    assert "Never impose an autonomous review/fix round cap" in prompt
    assert "review/fix rounds is not a reason to stop or escalate" in prompt
    assert "resolveReviewThread" in prompt
    assert "blanket-resolve threads" in prompt
    assert "<!-- pr-agent-generated -->" in prompt
    # Thread replies are posted under the owner's identity; without the marker
    # the merge gate counts them as human feedback newer than a Codex 👍.
    assert "ending each reply with `<!-- pr-agent-generated -->`" in prompt
    assert "top-level or inline thread reply, must end" in prompt
    assert "separate top-level success summary" in prompt


def test_merge_is_synchronous_and_retried_only_for_the_authorized_tested_head():
    workflow = _read(WORKFLOW)

    # Never leave an auto-merge request armed across head changes. Human and
    # Codex paths merge synchronously, and a successful Tests event retries
    # only after recovering authorization bound to that exact head.
    assert " --auto" not in workflow
    assert "--disable-auto" not in workflow
    assert "merge-after-tests:" in workflow
    assert 'live_head" != "$TESTED_HEAD' in workflow
    assert ".commit_id == $head" in workflow
    assert "sort_by(.submitted_at)" in workflow
    assert '"$latest_state" == "APPROVED"' in workflow
    assert '"$TESTED_HEAD" == "$approved_head"*' in workflow
    assert 'authorized_at=""' in workflow
    assert 'echo "authorized_at=${authorized_at}"' in workflow
    assert "authorized-at: ${{ github.event.review.submitted_at }}" in workflow
    assert "approval-id: ${{ github.event.review.id }}" in workflow
    assert "authorized-at: ${{ github.event.comment.updated_at }}" in workflow
    assert "merge-comment-id: ${{ github.event.comment.id }}" in workflow
    assert "authorized-at: ${{ steps.authorization.outputs.authorized_at }}" in workflow
    assert "approval-id: ${{ steps.authorization.outputs.approval_id }}" in workflow
    assert "merge-comment-id: ${{ steps.authorization.outputs.merge_comment_id }}" in workflow
    assert "approved-head: ${{ matrix.target.head }}" in workflow
    assert "authorized-at: ${{ matrix.target.authorized_at }}" in workflow
    assert workflow.count('--match-head-commit "$HEAD_SHA"') == 4
    assert workflow.count('if [[ "$state" == "MERGED" ]]') == 4
    assert workflow.count("was merged by another valid authorization") == 4


def test_merge_jobs_can_read_the_exact_heads_tests_run():
    workflow = _read(WORKFLOW)

    merge_permissions = (
        "permissions:\n      actions: read\n      contents: write\n      issues: read\n      pull-requests: write"
    )
    assert workflow.count(merge_permissions) == 4


def test_human_claude_fix_uses_a_distinct_unforgeable_reconcile_task():
    workflow = _read(WORKFLOW)
    prompt = _read(ROUTINE_PROMPT)

    activate_idx = workflow.find("activate:")
    fix_comment_idx = workflow.find("fix-comment-feedback:")
    assert activate_idx != -1 and fix_comment_idx > activate_idx
    activate_block = workflow[activate_idx:fix_comment_idx]
    assert "Task: reconcile-pr" in activate_block
    assert "Human override:" not in workflow
    assert "chatgpt-codex-connector[bot]" not in activate_block
    assert "max-review-fix-rounds:" not in workflow
    assert "expected-head: ${{ steps.live.outputs.head_sha }}" in activate_block
    assert "!startsWith(github.event.comment.body, '/claude-fix')" not in workflow
    assert "!contains(github.event.comment.body, '/claude-fix')" not in workflow
    assert "complete human-initiated reconciliation" in prompt
    assert "never impersonate the human reconciliation command" in prompt


def test_activate_requires_the_exact_claude_fix_command():
    """`startsWith(github.event.comment.body, '/claude-fix')` at the job level
    still matches /claude-fixation, /claude-fix-please, and content after
    the token on the same line. Parse the first line's first whitespace-
    delimited token in a live step so only an exact command invocation
    reaches the human-override reconcile-pr task and clears
    pr-agent-needs-human.
    """
    workflow = _read(WORKFLOW)

    activate_start = workflow.index("  activate:")
    feedback_start = workflow.index("  fix-comment-feedback:")
    activate = workflow[activate_start:feedback_start]

    assert "COMMENT_BODY: ${{ github.event.comment.body }}" in activate
    assert "first_line=$(printf '%s' \"$COMMENT_BODY\" | head -n1" in activate
    assert "first_token=${first_line%%[[:space:]]*}" in activate
    assert 'if [[ "$first_token" != "/claude-fix" ]]' in activate

    # Failing the exact-command check must land in the same open=false
    # early-exit that state / fork checks use, so downstream steps stay
    # gated on `steps.live.outputs.open == 'true'`.
    check_start = activate.index('if [[ "$first_token" != "/claude-fix" ]]')
    fi_marker = "\n          fi\n"
    then_block = activate[check_start : activate.index(fi_marker, check_start)]
    assert 'echo "open=false" >> "$GITHUB_OUTPUT"' in then_block
    assert "exit 0" in then_block

    # The ordinary feedback job runs for prefix lookalikes and mentions, then
    # suppresses itself only when the same exact-token test identifies a human
    # command. Bot-authored lookalikes still route as feedback.
    assert "Distinguish human reconciliation commands from feedback" in workflow
    assert "COMMENT_ASSOCIATION: ${{ github.event.comment.author_association }}" in workflow
    assert 'echo "feedback=true" >> "$GITHUB_OUTPUT"' in workflow
    assert 'if [[ "$first_token" == "/claude-fix"' in workflow
    assert 'echo "feedback=false" >> "$GITHUB_OUTPUT"' in workflow
    assert workflow.count("if: steps.route.outputs.feedback == 'true'") == 2


def test_escalation_clears_only_after_accepted_human_reconciliation():
    workflow = _read(WORKFLOW)

    activate_start = workflow.index("  activate:")
    feedback_start = workflow.index("  fix-comment-feedback:")
    activate = workflow[activate_start:feedback_start]
    assert "--remove-label pr-agent-needs-human" in activate
    assert "if: steps.routine.outputs.fired == 'true'" in activate
    remove_pos = activate.index("--remove-label pr-agent-needs-human")
    accepted_pos = activate.index("if: steps.routine.outputs.fired == 'true'")
    fire_pos = activate.index("id: routine")
    assert fire_pos < accepted_pos < remove_pos


def test_conflicted_unlabelled_prs_are_bootstrapped_safely():
    workflow = _read(WORKFLOW)

    assert "pull_request_target:\n    types: [opened, reopened, synchronize]" in workflow
    assert "discover-conflicts:" in workflow
    assert "reconcile-conflicts:" in workflow
    assert '--label "$AGENT_LABEL"' not in workflow
    assert "TRUSTED_PR_AUTHORS:" in workflow
    assert 'if [[ "$head_repo" != "$REPO" ]]' in workflow
    assert 'if [[ " $TRUSTED_PR_AUTHORS " != *" $author "* ]]' in workflow
    assert 'if [[ "$mergeable" == "CONFLICTING" ]]' in workflow
    assert "Task: reconcile-pr-auto" in workflow
    assert "expected-head: ${{ matrix.target.head }}" in workflow
    assert "max-review-fix-rounds:" not in workflow
    conflict_start = workflow.index("  reconcile-conflicts:")
    approval_start = workflow.index("  authorize_approval:")
    conflict_block = workflow[conflict_start:approval_start]
    assert "id: routine" in conflict_block
    assert "if: steps.routine.outputs.fired == 'true'" in conflict_block
    assert conflict_block.index("uses: ./.github/actions/fire-routine") < conflict_block.index(
        '--add-label "$AGENT_LABEL"'
    )


MAIN_HEALTH_WORKFLOW = ROOT / ".github/workflows/main-health.yml"


def _main_health_steps():
    return yaml.safe_load(_read(MAIN_HEALTH_WORKFLOW))["jobs"]["report"]["steps"]


def _gh_run_list_invocations(section):
    """Yield each ``gh run list`` invocation body from a routine-prompt section.

    A single invocation spans until an unbroken line that does not end with
    a shell continuation ``\\`` — the ``--jq`` filter is a multi-line
    single-quoted string, so the loop stops on its closing ``'`` line rather
    than at the first newline. The prose outside code fences is ignored.
    """
    lines = section.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()
        if stripped.startswith("gh run list "):
            block = [line]
            j = i + 1
            in_jq = False
            while j < len(lines):
                nxt = lines[j]
                block.append(nxt)
                if "--jq '" in nxt and nxt.count("'") % 2 == 1:
                    in_jq = True
                elif in_jq and "'" in nxt and nxt.count("'") % 2 == 1:
                    in_jq = False
                    if not nxt.rstrip().endswith("\\"):
                        break
                elif not in_jq and not nxt.rstrip().endswith("\\"):
                    break
                j += 1
            yield "\n".join(block)
            i = j + 1
            continue
        i += 1


def test_full_suite_runs_on_main_are_never_cancelled():
    workflow = _read(FULL_TEST_WORKFLOW)

    assert "cancel-in-progress: false" in workflow
    assert "cancel-in-progress: true" not in workflow


def test_red_main_is_tracked_in_one_issue():
    workflow = _read(MAIN_HEALTH_WORKFLOW)

    assert 'workflows: ["Full tests"]' in workflow
    # Only runs of main in this repository, never a PR's run.
    assert "github.event.workflow_run.head_branch == 'main'" in workflow
    assert "github.event.workflow_run.head_repository.full_name == github.repository" in workflow
    assert "github.event.workflow_run.event != 'pull_request'" in workflow
    # A green run closes the tracking issue; a red one opens or updates it.
    assert "gh issue close" in workflow
    assert "gh issue create" in workflow
    assert "gh issue comment" in workflow
    # Event data reaches the shell only through env vars, never interpolated.
    assert all("${{" not in step.get("run", "") for step in _main_health_steps())


def test_superseded_and_inconclusive_runs_do_not_drive_the_issue():
    workflow = _read(MAIN_HEALTH_WORKFLOW)

    # A rerun of an older run, or an out-of-order completion, must not
    # overwrite the issue with a stale result. Compare against the newest
    # run by ``createdAt`` (immutable to reruns), counting only runs whose
    # conclusion is one we drive the issue from: GitHub cancels a pending
    # run when a newer one queues, and that cancelled run must not make
    # the active run look superseded. ``timed_out`` and ``startup_failure``
    # are terminal unhealthy conclusions treated as red, so they count too.
    assert "--branch main --status completed" in workflow
    assert "--json databaseId,createdAt,conclusion" in workflow
    assert (
        '.conclusion == "success" or .conclusion == "failure"\n'
        '                                or .conclusion == "timed_out" or .conclusion == "startup_failure"'
    ) in workflow
    assert "sort_by(.createdAt) | reverse" in workflow
    assert '"$latest_id" != "$RUN_ID"' in workflow


def test_timed_out_and_startup_failure_runs_are_treated_as_red():
    workflow = _read(MAIN_HEALTH_WORKFLOW)

    # A ``Full tests`` run that hits its per-job timeout or ends with
    # ``startup_failure`` never successfully tested ``main``, so it must
    # open (or update) the tracking issue rather than being skipped. The
    # ``if`` gate on the job admits all four unhealthy terminal conclusions
    # alongside ``success`` (the close-issue branch); the body's non-success
    # path then opens/updates the issue for the failure-like ones.
    assert "conclusion == 'timed_out'" in workflow
    assert "conclusion == 'startup_failure'" in workflow


def test_stale_attempt_events_of_the_latest_run_are_skipped():
    workflow = _read(MAIN_HEALTH_WORKFLOW)

    # GitHub keeps the same databaseId across reruns while incrementing
    # ``run_attempt`` and potentially changing the conclusion, so the
    # ``latest_id == RUN_ID`` check alone lets a stale attempt's completion
    # (the original failure event delivered after a rerun succeeded, or a
    # rerun's failure delivered before an even later rerun's success) drive
    # the issue. Compare this event's attempt AND conclusion against the
    # run's current state before continuing.
    assert "RUN_ATTEMPT: ${{ github.event.workflow_run.run_attempt }}" in workflow
    assert '--json attempt,conclusion' in workflow
    assert '"$current_attempt" != "$RUN_ATTEMPT"' in workflow
    assert '"$current_conclusion" != "$CONCLUSION"' in workflow


def test_each_incident_gets_one_accepted_fix_request():
    workflow = _read(MAIN_HEALTH_WORKFLOW)
    prompt = _read(ROOT / "docs/pr-agent-routine-prompt.md")
    steps = _main_health_steps()

    # Fire unless the issue already records an accepted request, counting
    # only this workflow's own comments (anyone can comment on the issue).
    run = next(step["run"] for step in steps if step.get("id") == "issue")
    assert 'github-actions[bot]' in run
    assert "$REQUESTED_MARKER" in run
    assert "if (( requested == 0 )); then" in run
    # The record is written only after the routine accepted the fire, so a
    # gated-off or rejected dispatch is retried on the next red run.
    record = next(step for step in steps if step.get("name") == "Record the fix request on the issue")
    assert record["if"] == "steps.fire.outputs.fired == 'true'"
    assert "${REQUESTED_MARKER}" in record["run"]
    assert "Task: fix-main" in workflow
    assert "## Task: `fix-main`" in prompt
    assert "| `fix-main`" in prompt
    # The routine itself stops if the incident closed or a fix PR is open.
    assert "Refs #$ISSUE" in prompt
    # Match the exact issue: a substring test would let #12 match "Refs #123".
    assert 'test(\\"Refs #$ISSUE([^0-9]|$)\\")' in prompt
    assert 'contains(\\"Refs #$ISSUE\\")' not in prompt


def test_fix_main_revalidates_workflow_run_before_diagnosing_and_publishing():
    prompt = _read(ROUTINE_PROMPT)

    # The main-health fire is one-shot per incident, so the accepted-request
    # marker prevents any newer red run from firing a second session. If a
    # newer commit concludes a different failure while this session is queued
    # or working, diagnosing the original run and branching from current main
    # leaves the newer failure unhandled — verify WORKFLOW_RUN is still the
    # newest conclusive Full tests run before diagnosis, and again before
    # publication (mirrors main-health.yml's own supersession lookup).
    fix_main_start = prompt.index("## Task: `fix-main`")
    fix_main_end = prompt.index("## Absolute Rules", fix_main_start)
    section = prompt[fix_main_start:fix_main_end]

    supersede_lookup = (
        'gh run list --workflow "Full tests" --branch main '
        "\\\n     --limit 100 "
        "\\\n     --json databaseId,createdAt,conclusion,status "
        "\\\n     --jq '[.[] | select(.status != \"completed\""
        "\n                          or .conclusion == \"success\" or .conclusion == \"failure\""
        "\n                          or .conclusion == \"timed_out\""
        "\n                          or .conclusion == \"startup_failure\")]"
        "\n           | sort_by(.createdAt) | reverse"
    )
    assert section.count(supersede_lookup) == 2

    # Pre-diagnosis: switch to the newer failure, or exit silently if the
    # newer run went green (main is now healthy). An in-flight newer run
    # (queued or in progress) falls through — its result is not yet known
    # and diagnosing WORKFLOW_RUN (a real past failure) is still meaningful.
    assert 'if [ -n "$latest_id" ] && [ "$latest_status" = "completed" ]; then' in section
    assert '[ "$latest_conclusion" = "success" ] && exit 0' in section
    assert 'WORKFLOW_RUN="$latest_id"' in section

    # Pre-publication: exit silently only when the incident is resolved
    # (a newer success closed main). A newer failure that concluded during
    # diagnosis is a different situation: the accepted-request marker
    # prevents another dispatch, so abandoning here strands the incident;
    # publish the fix and let the fix PR's own CI catch regressions. An
    # in-flight newer run is also not a reason to abandon — its result is
    # unknown, so the publish check requires status == "completed".
    assert (
        '[ -z "$latest_id" ] || [ "$latest_status" != "completed" ] \\\n'
        '     || [ "$latest_conclusion" != "success" ] || exit 0'
    ) in section


def test_fix_main_revalidation_survives_an_in_flight_rerun_of_workflow_run():
    prompt = _read(ROUTINE_PROMPT)

    # When ``WORKFLOW_RUN`` is manually rerun while this session is
    # running, its shared ``databaseId`` becomes queued or in progress.
    # ``--status completed`` would then hide the rerun and the lookup
    # would fall back to an older run — an older green would exit
    # silently and strand the incident, an older failure would diagnose
    # the wrong logs. The revalidation therefore inspects the newest run
    # regardless of status, admits queued/in-progress rows into the
    # newest-first selection, and skips the ID/conclusion checks when
    # that newest row is not yet ``completed``.
    fix_main_start = prompt.index("## Task: `fix-main`")
    fix_main_end = prompt.index("## Absolute Rules", fix_main_start)
    section = prompt[fix_main_start:fix_main_end]

    # Look only at ``gh run list`` invocations, not at the prose that
    # names ``--status completed`` to explain what NOT to do.
    for gh_call in _gh_run_list_invocations(section):
        assert "--status completed" not in gh_call, gh_call
        assert '.status != "completed"' in gh_call
        assert '--json databaseId,createdAt,conclusion,status' in gh_call

    assert 'latest_status=$(printf %s "$latest" | jq -r' in section


def test_fix_main_revalidation_keys_on_conclusion_not_run_id():
    prompt = _read(ROUTINE_PROMPT)

    # GitHub retains ``databaseId`` when a run is rerun, so an ID-only check
    # cannot tell a same-ID success rerun (main is now green) from the
    # original failure that fired this session. Both revalidations therefore
    # key on ``conclusion``: pre-diagnosis exits on any newer success and
    # only switches ``WORKFLOW_RUN`` when the newest conclusive run is a
    # different run in failure; pre-publication exits on any newer success
    # and continues on any newer failure so the accepted request is not
    # stranded when a different failing run supersedes it.
    fix_main_start = prompt.index("## Task: `fix-main`")
    fix_main_end = prompt.index("## Absolute Rules", fix_main_start)
    section = prompt[fix_main_start:fix_main_end]

    # Neither snippet drops out of revalidation when the newest conclusive
    # run's databaseId happens to match WORKFLOW_RUN — those checks are
    # unconditional (a same-ID rerun's new conclusion is what matters).
    assert '[ "$latest_id" != "$WORKFLOW_RUN" ]' not in section
    assert '[ "$latest_id" = "$WORKFLOW_RUN" ] || exit 0' not in section

    # Pre-diagnosis: the switch to a newer run is guarded by an inequality
    # check, so a same-ID failure (a rerun of WORKFLOW_RUN that failed
    # again) keeps WORKFLOW_RUN pointing at itself rather than reassigning.
    assert '[ "$latest_id" = "$WORKFLOW_RUN" ] || WORKFLOW_RUN="$latest_id"' in section


def test_fix_main_dispatch_is_gated_until_stored_routine_prompt_is_synced():
    steps = _main_health_steps()

    # The routine prompt is pasted in by hand; until it knows ``fix-main`` a
    # fire would be accepted and do nothing, so the checkout and the fire sit
    # behind a repository variable the maintainer flips after syncing it.
    gated = [
        step for step in steps
        if step.get("uses", "").startswith(("actions/checkout", "./.github/actions/fire-routine"))
    ]
    assert len(gated) == 2
    for step in gated:
        assert "vars.MAIN_HEALTH_ENABLE_FIX_MAIN == 'true'" in step["if"]
    assert any(
        "vars.MAIN_HEALTH_ENABLE_FIX_MAIN != 'true'" in step.get("if", "") for step in steps
    )
